### ISSUE TITLE
Blocks Not Pushing

### ISSUE THREAD

**Issue by rcpauor32** [BooLAW/Zelda-Project#26]
**Type:**    
UI
Code *
Mechanics
Design
Animation
Tilesets
Audio

**Severity:**    
Crash 
Game Stopping *
Minor/Other

**What Happens:**   
Blocks cannot be pushed from bottom or top position. 

**Expected Result:**
Blocks should be pushed from any direction.

**How to reproduce:**    
Try to push a block from up or down (press space)

**Build/Date:**    
v.0.4.5
04/04/2017

**Comment by MarcFly** [comment]
The Check Collision works bad when lloking at higher values, but well, in lower ones.
For the moment I reverse reseult for if so it works when pushing towards
