### ISSUE TITLE
Game shows Enemies sprites

### ISSUE THREAD

**Issue by Tr4fa1Gar** [BooLAW/Zelda-Project#58]
**Type:**    
UI
Code
Mechanics
Design
Animation
Tilesets
Audio

**Severity:**    
Game Stopping

**What Happens:**    
When you press continue appears the spritesheet.
![image](https://cloud.githubusercontent.com/assets/17140515/25847462/903e78c6-34b6-11e7-8570-809f288ab640.png)

**Expected Result:**
Should not start the game in thw first loop when you press continue.

**How to reproduce:**    
Press continue the first time you open the game.

**Build/Date:**    
May 9th. 0.7

**Comment by MarcFly** [comment]
This bug happens randomly, it wil blit random full spritesheets or things over the whole size of the dungeon. Not only with enemies, but with every other spritesheet available.
