### ISSUE TITLE
F4 does not do anything

### ISSUE THREAD

**Issue by rodrigodpl** [BooLAW/Zelda-Project#67]
**Type:**    
Design

**Severity:**    
Minor/Other

**What Happens:**    
README says F4 changes scenes but it does not do anything.

**Expected Result:**
Change README / change scene

**How to reproduce:**    
Always

**Build/Date:**    
0.7

**Comment by MarcFly** [comment]
F4 is a Debug feature, which is not enabled, should be out of the readme
