### ISSUE TITLE
Big 25, flickering blocking screen

### ISSUE THREAD

**Issue by JosepContact** [BooLAW/Zelda-Project#68]
**Type:**    
Code

**Severity:**    
Game Stopping

**What Happens:**    
Big 25, flickering blocking screen
**Expected Result:**
Nothing blocking screen
**How to reproduce:**    
Start the game, it sometimes happens
**Build/Date:**    
Latest

**Comment by MarcFly** [comment]
Happens, not only with the 25/0, happens with full spritesheets, mainly of enemies and projectile of enemies
